#!/usr/bin/env sh

if [ "$#" -eq 1 ]
then
 echo "creating directory tree..."
 mkdir "$1"
 cd "$1"
 mkdir css 
 mkdir images
 mkdir scripts
 echo "making boilerplate index.html, styles.css and README.md"
 cp /Users/jasontuttle/Developer/templates/index.html ./index.html
 cp /Users/jasontuttle/Developer/templates/README.md ./README.md
 cp /Users/jasontuttle/Developer/templates/styles.css css/styles.css
 echo "setting up git repo..."
 git init
 git add .
 git commit -m 'initial commit'
 echo "creating GitHub repo..."
 hub create -d "$1"
 echo "pushing to GitHub..."
 git push origin master
 echo "Done!"
 exit 0
else
 echo "Usage: gen_site [name]"
 exit 1
fi
